### ISSUE TITLE
Please release version with moneta 1.3

### ISSUE THREAD

**Issue by ptahchiev** [zalando/jackson-datatype-money#112]
Moneta 1.3 is out. Do you support it? Can you please release a version to maven central that updates the dependency.
Thank you.

**Comment by whiskeysierra** [comment]
Any major change that would break our module? Did you try it?

**Comment by ptahchiev** [comment]
I haven't tried it yet ..

**Comment by whiskeysierra** [comment]
See #113, tests are working without any modification. You should be safe when upgrading to the newest version.
