### ISSUE TITLE
Unwanted transitive dependency to jdk8 version of money api and ri

### ISSUE THREAD

**Issue by jhorstmann** [zalando/jackson-datatype-money#20]
This library should be compatible with both the jdk8 and jdk7-backport versions of java money, that's why we moved the dependencies into separate profiles. Unfortunately this does not seem to work, as this output from `mvn dependency:tree` from a project shows:

    [INFO] +- org.zalando:jackson-datatype-money:jar:0.6.0:compile
    [INFO] |  +- javax.money:money-api:jar:1.0:compile
    [INFO] |  \- org.javamoney:moneta:jar:1.0:compile

Looking at the [deployed pom][1], there is no direct dependency outside of profiles to api or ri, and I did not think that mvn would activate profiles inside a dependency.

 [1]: https://oss.sonatype.org/service/local/repositories/releases/content/org/zalando/jackson-datatype-money/0.6.0/jackson-datatype-money-0.6.0.pom

**Comment by whiskeysierra** [comment]
Mmh, interesting. Our current approach was to treat both versions, java 7 and 8, equal, i.e. we don't favor one over the other. What if we in fact do add a direct dependency to the java 8 version of java money and change the way we support the backport by letting users explicitly exclude them:

```xml
<dependency>
  <groupId>org.zalando</groupId>
  <artifactId>jackson-datatype-money</artifactId>
  <version>${jackson-datatype-money.version}</version>
  <exclusions>
    <exclusion>
      <groupId>javax.money</groupId>
      <artifactId>money-api</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.javamoney</groupId>
      <artifactId>moneta</artifactId>
    </exclusion>
  </exclusions>
<dependency>
    <groupId>javax.money</groupId>
    <artifactId>money-api-bp</artifactId>
    <version>${java-money.version}</version>
</dependency>
<dependency>
    <groupId>org.javamoney</groupId>
    <artifactId>moneta-bp</artifactId>
    <version>${java-money.version}</version>
</dependency>
```

It's obviously a bit more cumbersome to use, but I have the assumption that the majority of clients would use the reference implementation, rather than the backport. Thoughts?

**Comment by jhorstmann** [comment]
Agree, it would be ok if the backport is slightly more difficult to use. We should still try to run the tests with both implementations, this would be more difficult with the above approach.

And I still want to find out why this transitive dependency currently exists, as this contradicts my understanding of maven dependencies.

**Comment by whiskeysierra** [comment]
> And I still want to find out why this transitive dependency currently exists, as this contradicts my understanding of maven dependencies.

We are using

```xml
<activation>
  <activeByDefault>true</activeByDefault>
</activation>
```

for the `jdk8` profile. I don't remember why I added this.

**Comment by jhorstmann** [comment]
Yes, but the dependency is still in a profile, even in the deployed pom (https://oss.sonatype.org/service/local/repositories/releases/content/org/zalando/jackson-datatype-money/0.6.0/jackson-datatype-money-0.6.0.pom). I can't find this behaviour described in the documentation and will investigate this today.
