### ISSUE TITLE
CNH currency is not being deserialized

### ISSUE THREAD

**Issue by towojtek** [zalando/jackson-datatype-money#213]
## Description
com.fasterxml.jackson.databind.JsonMappingException: Unknown currency code: CNH

## Expected Behavior
Handling CNH currency by lib

## Actual Behavior
com.fasterxml.jackson.databind.JsonMappingException: Unknown currency code: CNH

## Possible Fix
Extend list of currencies.

## Steps to Reproduce

1. Run junit test with CNH currency.

**Comment by whiskeysierra** [comment]
We rely on java money/moneta as the underlying library to manage currencies, so this is out of our reach.
From what I can tell, CNH is not a valid ISO-4217 currency code and therefore not supported by java.util.Currency etc.

See also
- https://stackoverflow.com/questions/50677177/work-around-for-adding-cnh-as-a-valid-currency-in-java-util-currency
- https://www.iso.org/iso-4217-currency-codes.html
