### ISSUE TITLE
Version 1.1.1 in Maven central is using NumberValue not BigDecimal 

### ISSUE THREAD

**Issue by djfried** [zalando/jackson-datatype-money#221]
https://github.com/zalando/jackson-datatype-money/blob/f1f42349debd276bdf7413067d971ebee70ef032/src/main/java/org/zalando/jackson/datatype/money/MonetaryAmountFactory.java#L16

Wondering why there is a mismatch or what version uses BigDecimal

**Comment by whiskeysierra** [comment]
Latest version in master is not released, I assume.

**Comment by whiskeysierra** [comment]
I released 1.2.0 just now.

**Comment by djfried** [comment]
Thanks will check it out!
