### ISSUE TITLE
Strange behaviour in case of 100.00 EUR value

### ISSUE THREAD

**Issue by mastersimon** [zalando/jackson-datatype-money#24]
Hi all,

I´m wondering why this test runs into an error:

```java
@Test
    public void shouldSerializeWithoutFormattedValueIfFactoryProducesNull() throws JsonProcessingException {
        final ObjectMapper unit = new ObjectMapper()
                .registerModule(new MoneyModule());
        
        final String expected = "{\"amount\":100.00,\"currency\":\"EUR\"}";
        final String actual = unit.writeValueAsString(Money.of(100.00, "EUR"));

        assertThat(actual, is(expected));
    }
```

Result:
```bash
java.lang.AssertionError: 
Expected: is "{\"amount\":100.00,\"currency\":\"EUR\"}"
     but: was "{\"amount\":1E+2,\"currency\":\"EUR\"}"
Expected :{\"amount\":100.00,\"currency\":\"EUR\"}
Actual   :{\"amount\":1E+2,\"currency\":\"EUR\"}
```

**Comment by whiskeysierra** [comment]
`1E+2` is a valid JSON number that is equvialent to `100`:

![JSON Number](http://json.org/number.gif)

If you want to suppress that behaviour you can enable `WRITE_BIGDECIMAL_AS_PLAIN`:

    new ObjectMapper()
            .enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN)
            .registerModule(new MoneyModule());

**Comment by whiskeysierra** [comment]
It will actually produce `{"amount":100,"currency":"EUR"}` since the trailing zeros of the fraction aren't necessary.

**Comment by jhorstmann** [comment]
To clarify, it is the money implementation that removes trailing zeroes, not jackson. To get a formatted output you can pass in a `MonetaryAmountFormatFactory` implementation to the `MoneyModule`, as described in the README.
