### ISSUE TITLE
Added a link from main jackson page

### ISSUE THREAD

**Issue by cowtowncoder** [zalando/jackson-datatype-money#3]
(apologies for adding a "non-issue" issue, but figured this is a reasonable way to contact authors -- will be happy to communicate using better methods too afterwards -- you can contact me via `tatu` at fasterxml dot com for example, in addition to referencing via my account)

First of all, thank you for writing this datatype module. I think it is great to get serialization support for new standard Java APIs from get go.

Second: I hope you don't mind my adding a link on https://github.com/FasterXML/jackson to point to this project. I mostly mention this because sometimes authors wish to reach certain version before announcing or something; if so, just let me know. Ditto for any changes to verbiage of the link; will be happy to update it any way you want, including mention of sponsors for work or such (we like to give credit to companies that help OSS development).

**Comment by sdeleuze** [comment]
It would be nice to have this module supported by Jackson since we are talking about the standard Java Money API. Any thoughts ?

**Comment by whiskeysierra** [comment]
> It would be nice to have this module supported by Jackson since we are talking about the standard Java Money API. Any thoughts ?

Absolutely. My only concern is that there might be several different ways to serialize money, e.g.

    {"amount": 9.95, "currency": "EUR"}

or 

    {"amount": 995, "scale": 2, "currency": "EUR"}

or

    {"amount": "9.95", "currency": "EUR"}

All of which have different pros and cons (readability for humans/devs vs. incompatible parsers that read double values).

We are not exactly sure whether we want to support all of them or find the one that works for us.

**Comment by whiskeysierra** [comment]
> I mostly mention this because sometimes authors wish to reach certain version before announcing or something; if so, just let me know.

@cowtowncoder I'm fine with being listed there (actually kind of proud, to be honest), but since we are still at 0.x.y maybe it should have a not saying it's still alpha/beta/early development?

Come to think of it, maybe we should tell that in our readme :)

**Comment by cowtowncoder** [comment]
@sdeleuze I think that the proper way to support new standard Java type additions is via Jackson modules, even if it was possible to add support directly in Jackson databind module. This because number of different datatype libraries keeps on growing, and most users do not use all of these types.
But at practical level it is often not possible as core databind only requires JDK 6, and many new additions are based on later JDK versions.

There is room for combining updates on per-JDK level, when standard datatypes are incorporated in JDK itself. So, for example, all new datatypes introduced by JDK 8 should be included in a single `jackson-datatype-jdk8` module.
Frameworks can then choose to include certain set of standard Jackson datatype modules; many include Joda and Guava modules, for example.

**Comment by sdeleuze** [comment]
@cowtowncoder I totally agree with using a separated Jackson module for that, My request was more about having this module supported as an official module: hosted on https://github.com/FasterXML and released at the same time than Jackson itself, like other official modules. Sorry if it was not clearly expressed.

Side note: it seems that JSR 354 won't be part of Java 9.

**Comment by cowtowncoder** [comment]
@sdeleuze Ah ok. Yes, that makes sense.
