### ISSUE TITLE
Concrete RI type Money not accepted for serialization

### ISSUE THREAD

**Issue by keyboardsamurai** [zalando/jackson-datatype-money#38]
Serializing a class that uses the reference implementation `Money` class instead of `javax.money.MonetaryAmount` will fail with the following message:

`com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.javamoney.moneta.Money]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)`

Example class:

```
import org.javamoney.moneta.Money;

public class MyValueObject {
    public Money price;
    public String name;
    public MyValueObject() {
    }
    public MyValueObject(Money money, String name) {
        this.price = money;
        this.name = name;
    }
}
```
If you use MonetaryAmount instead, everything works fine. 

I would expect that either the docs mention that you cannot use RI-Types in your objects, or make the Serializer check for classes that implement MonetaryAmount. 

See example JUnit test project here: [test-money-json.zip](https://github.com/zalando/jackson-datatype-money/files/482284/test-money-json.zip)

**Comment by whiskeysierra** [comment]
Hi, thanks for raising the issue. Personally I'd refrain from coding against concrete implementation rather than abstractions. But I see some value in this and no reason not to support it. I'll take a look.

**Comment by whiskeysierra** [comment]
@keyboardsamurai I opened #39 which includes new tests for deserializing into Money, FastMoney and RoundedMoney respectively.

**Comment by whiskeysierra** [comment]
@keyboardsamurai I deployed 0.10.0 to central, could take a while before it's available.

**Comment by keyboardsamurai** [comment]
That was quick 👍  I verified and it's working. Thank you.
