### ISSUE TITLE
Custom naming for currency and amount fields

### ISSUE THREAD

**Issue by joris77** [zalando/jackson-datatype-money#40]
Would it be possible to make the names of the MonetaryAmount configurable? So for example a monetary amount would be serialized like this if you configure the amount field to be named value:

`{
  "currency" : "EUR",
  "value" : 100
}`

**Comment by whiskeysierra** [comment]
We are using an intermediate object right now to do the de/serialization (`MoneyNode`). The name is pretty much hard coded there right now. That's something I wanted to get rid for a while now, but had no real reason/incentive to do so. Making the name configurable would actually be one. I'll take a look.

**Comment by whiskeysierra** [comment]
@joris77 Can you take a look at #41?

**Comment by joris77** [comment]
Yes i looked at it looks exactly what we need. I will try it. Thank you very much for the quick response and fix

**Comment by whiskeysierra** [comment]
@joris77 I just released 0.11.0. Should be available in central soon. Thanks for the suggestion/issue.
