### ISSUE TITLE
Type Id Handling not supported

### ISSUE THREAD

**Issue by stefanzilske** [zalando/jackson-datatype-money#46]
Hi Folks,

I want to serialise Money types with Type Info, so that I can properly use it in serialised collections. In order to achieve this, I use Jackson DefaultTyping for polymorphic serialisation. Otherwise, type information will get lost when I serialise a Collection.

This is my (simplified) scenario:

```java
public class ParentDomainObject {
  private Long id;
  private Set<ChildDomainObject> children;
}

public class ChildDomainObject {
  private Long id;
  private MonetaryAmount cost;
}

public class SomeHandler {
  public void serialiseMyDomainObjects() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new MoneyModule());
    mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.OBJECT_AND_NON_CONCRETE);

    ParentDomainObject o1 = new ParentDomainObject();
    // add some child objects

    ParentDomainObject o2 = new ParentDomainObject();
    // add some child objects

    mapper.writeValueAsString(Sets.asSet(o1, o2));
  }
}
```

When I try to run this, I get the following Exception:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type id handling not implemented for type org.javamoney.moneta.Money (by serializer of type org.zalando.jackson.datatype.money.MonetaryAmountSerializer)
```

I hope you get the point. Is this simply not supported (at the moment) or is there any way to work around this?

Cheers,
Stefan

**Comment by whiskeysierra** [comment]
What's your goal? Do you want to preserve the type information, i.e. which implementation of MonetaryAmount it was when serializing?

**Comment by stefanzilske** [comment]
Yes, exactly. 

If I don't use the DefaultTyping, Jackson will not be able to deserialise the DomainObjects inside the collection again, as it has no type information. DefaultTyping add the necessary type information, but it does not work with Money types.

**Comment by whiskeysierra** [comment]
@stefanzilske Can you take a look at #47?
