### ISSUE TITLE
Make deserialization working without jackson-module-parameter-names

### ISSUE THREAD

**Issue by sdeleuze** [zalando/jackson-datatype-money#5]
Currently it seems it is not possible de deserialize data without having `jackson-module-parameter-names` dependency and registering it in Jackson `ObjectMapper`. It would be nice to avoid this by adding `@JsonCreator` and `@JsonProperty("foo")` annotations to classes like  `MoneyNode`.

**Comment by snicoll** [comment]
:+1:

**Comment by sdeleuze** [comment]
This issue seems to be itself a continuation of https://github.com/zalando/jackson-datatype-money/pull/4

**Comment by sdeleuze** [comment]
Awesome, Thanks! We would like to use `jackson-datatype-money` for our Spring One conference demo (it begins 09/14) so if there could be a 0.3.0 release before this date it would be just perfect!

**Comment by whiskeysierra** [comment]
> so if there could be a 0.3.0 release before this date it would be just perfect!

I released the current master as 0.3.0 to central right now. Should be available in the next hours.

**Comment by sdeleuze** [comment]
Thanks again!

**Comment by whiskeysierra** [comment]
No problem! Thanks for the pull request :+1:
