### ISSUE TITLE
Change amount parameter type from BigDecimal to Number

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/jackson-datatype-money#51]
`MonetaryAmountFactory.create(BigDecimal, CurrencyUnit)` should be changed to use either `Number` or `NumberValue`.

**Comment by AlexanderYastrebov** [comment]
Two of three impls currently lack constructors accepting NumberValue, so probably it should be Number.
Also with Number this change looks like non breaking.

**Comment by whiskeysierra** [comment]
NumberValue extends Number, so that would work. Changing the parameter to Number would be breaking since existing implementations (outside of our control) would then not be compatible anymore.

**Comment by AlexanderYastrebov** [comment]
> NumberValue extends Number, so that would work.

yes, but then you have to extract number from NumberValue back and you have to construct NumberValue somehow as well to pass it in.

> Changing the parameter to Number would be breaking 
yes, it would not be binary compatible but should compile just fine

**Comment by whiskeysierra** [comment]
> yes, but then you have to extract number from NumberValue back

Why?

> you have to construct NumberValue somehow as well to pass it in.

`DefaultNumberValue.of(..)`

> but should compile just fine

No, since existing implementations will have `BigDecimal` but our new spec requires `Number` or `NumberValue`. As a return value that would be source compatible, but not with parameters.

**Comment by AlexanderYastrebov** [comment]
Ah, I was thinking about client classes which _use_ MonetaryAmountFactory, but impls would break, yes.

You have to extract number from NumberValue back since 2 of 3 impls of MonetaryAmount do not support constructors accepting NumberValue

**Comment by whiskeysierra** [comment]
> You have to extract number from NumberValue back since 2 of 3 impls of MonetaryAmount do not support constructors accepting NumberValue

`NumberValue` extends `Number`, you can just pass it along.
