### ISSUE TITLE
Hide de/serializer implementations

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/jackson-datatype-money#53]
Right now all de/serializer implementations are public so client could use them directly, if needed. We should consider making them package private and only open them up if the need arises. It would reduce our public API surface drastically.

**Comment by AlexanderYastrebov** [comment]
One big issue with this is that it will not allow clients to easily upgrade to 2.0

**Comment by whiskeysierra** [comment]
Clients that actually use them right now?

**Comment by AlexanderYastrebov** [comment]
Yes

**Comment by whiskeysierra** [comment]
Which is fine, technically. We are creating a new major version, so we can have breaking changes. If somebody needs access and wants to switch to 2.x he needs to open an issue and explain his requirement.
