### ISSUE TITLE
MonetaryAmountDeserializer currency

### ISSUE THREAD

**Issue by wwadge** [zalando/jackson-datatype-money#6]
I'm having trouble with the MonetaryAmountDeserializer.

When jackson attempts to create a new MoneyNode, it fails in calling the constructor because  CurrencyUnit is an interface and it doesn't know what concrete type to use.

The fix is easy - change the currency to a string and then convert internally:

```
        @JsonCreator
    MoneyNode(@JsonProperty("amount") final BigDecimal amount,
              @JsonProperty("currency") final String currency) {
        this.amount = amount;
        this.currency = CurrencyUnitBuilder.of(currency, "default").build();
    }
````

**Comment by jhorstmann** [comment]
Can you share a testcase demonstrating this problem? This should work, as shown in the unit test here: https://github.com/zalando/jackson-datatype-money/blob/master/src/test/java/org/zalando/jackson/datatype/money/MonetaryAmountDeserializerTest.java#L39

**Comment by wwadge** [comment]
I apologies - this must have been something else for I can no longer reproduce it reliably :-/

**Comment by whiskeysierra** [comment]
I'd suspect this behaviour if one would use the `MonetaryAmountDeserializer` on its own, without using the Module.
