### ISSUE TITLE
Restore CurrencyUnitDeserializer?

### ISSUE THREAD

**Issue by sappenin** [zalando/jackson-datatype-money#67]
Any reason `CurrencyUnitDeserializer` was removed in the [9/1 commit](64cdfe7f909bed4122856a400ef1e8490a94883b)?

It would be nice to use this library to serialize/deserialize standalone fields of type [javax.money.CurrencyUnit](https://github.com/JavaMoney/jsr354-api/blob/master/src/main/java/javax/money/CurrencyUnit.java).

**Comment by whiskeysierra** [comment]
We removed it in an attempt to reduce the public API to a workable minimum. I did this under the assumption that de/serializing `MonetaryAmount` instances is the primary if not even the only use case. I guess I was wrong. I'll re-create the support for `CurrencyUnit`.

**Comment by sappenin** [comment]
Awesome - thanks for being open to the request! In my case, I have an API that's advertising a currency unit by itself.

**Comment by whiskeysierra** [comment]
@sappenin Feel free to take a look at #68.

**Comment by sappenin** [comment]
Looks great, thanks!

**Comment by whiskeysierra** [comment]
@sappenin I released 1.0.0-RC2 to central just now.
