### ISSUE TITLE
RestTemplate Integration

### ISSUE THREAD

**Issue by pluttrell** [zalando/jackson-datatype-money#70]
Is there some additional configuration required to get deserialization working with Spring's `RestTemplate`?

I'm getting the following error:

```
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Can not construct instance of javax.money.MonetaryAmount: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of javax.money.MonetaryAmount: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: java.io.PushbackInputStream@2065cbae; line: 2, column: 13] (through reference chain: com.mypackage.PriceResource["price"])
```

I'm using version `org.zalando:jackson-datatype-money:1.0.0-RC2` with `'org.javamoney:moneta:1.1'` and am trying to deserialize:

```json
{
    "price": {
        "amount": 1799.99,
        "currency": "USD"
    }
}
```

into:

```java
import javax.money.MonetaryAmount;
import org.springframework.hateoas.ResourceSupport;

public class PriceResource extends ResourceSupport {
  private MonetaryAmount price;
  public PriceResource() {}
  public MonetaryAmount getPrice() {
    return price;
  }
  public void setPrice(MonetaryAmount price) {
    this.price = price;
  }
}
```

Using a `RestTemplate` built as follows:

```java
RestTemplate restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory());
restTemplate.getMessageConverters().removeIf(messageConverter -> messageConverter.getClass() == MappingJackson2HttpMessageConverter.class);
restTemplate.getMessageConverters().add(new MappingJackson2HttpMessageConverter(objectMapper));
```

where the `objectMapper` is created by SpringBoot (v1.5.7) and injected into the previous method and supplied the `MoneyModule` via the following:

```java
@Configuration
class JacksonConfig {
  @Bean
  public MoneyModule moneyModule() {
    return new MoneyModule();
  }
}
```

To show that the `RestTemplate` has an `ObjectMapper` with the `MoneyModule`, here's the instance view in the debugger right after catching the above exception:

<img width="1058" alt="billingserviceclient_java_-_expressplay_services_-____dev_repos_exp-services_bitbucket_" src="https://user-images.githubusercontent.com/4094051/30960403-bd28480c-a3f7-11e7-92a6-0b7f0f05f415.png">

Note that I've also tried both of the following configs, as the `README.md` wasn't clear if was necessary or not, however both generated the same error as above:

```java
@Configuration
class JacksonConfig {
  @Bean
  public MoneyModule moneyModule() {
    return new MoneyModule().withMoney();
  }
}
```

```java
@Configuration
class JacksonConfig {
  @Bean
  public MoneyModule moneyModule() {
    return new MoneyModule().withMonetaryAmount(Money::of);
  }
}
```

**Comment by whiskeysierra** [comment]
Are you sure this converter is used? The third line in your screenshot shows another converter for jackson.

**Comment by pluttrell** [comment]
What do you mean by converter? I'm not very familiar with Jackson internals, I've always added support for additional types like this through their `Module` feature. And the `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule` right above it is properly serializing and deserializing Java8 date/time types.

**Comment by whiskeysierra** [comment]
The third line from the very top. I'm talking about a message converter that is also registered with Spring. Have you verified with your debugger which converter is actually running?

**Comment by pluttrell** [comment]
How do I verify which converter is running?

**Comment by pluttrell** [comment]
Good catch. The `TypeConstrainedMappingJackson2HttpMessageConverter` was indeed being used and the `ObjectMapper` it contained did not have the `MoneyModule`, only this one: `org.springframework.hateoas.hal.Jackson2HalModule`.  The contentType of the response I'm receiving is `application/hal+json;charset=UTF-8`, which appears to have triggered that converter.

So with that root cause, do you have any recommendations as to how to resolve the problem?

**Comment by whiskeysierra** [comment]
Any idea who registered the `TypeConstrainedMappingJackson2HttpMessageConverter`? My best bet would be to merge both, i.e. register the `Jackson2HalModule` in the other object mapper and re-use it for both use cases. If that doesn't work, I'd try to register the `MoneyModule` in both ObjectMappers.

**Comment by whiskeysierra** [comment]
@pluttrell Did you manage to resolve your issue? Can I close this?
