### ISSUE TITLE
Adjust No-Args Constructor in CurrencyUnitSerializer to be public?

### ISSUE THREAD

**Issue by sappenin** [zalando/jackson-datatype-money#75]
Is there any chance we could change the no-args constructor of `CurrencyUnitSerializer` to have `public` visibility? 

Not sure if there's any particular reason for it to be `package-private`, but currently it's not possible to use this serializer in a SimpleModule (i.e., without using the `MoneyModule` or some other class in the `org.zalando.jackson.datastype.money` package).

**Comment by whiskeysierra** [comment]
I always try to minimize the public API as much as possible. Can you describe your use case? Why can't you just register the MoneyModule?

**Comment by sappenin** [comment]
Sure thing -- in some of our APIs, we have resource representations that model something like a bank "Ledger" -- that representation has no money values in it, but one of the attributes is a currency code (`CurrencyUnit` type) that indicates the type of asset held on a given ledger.

I was hoping to be able to register a `SimpleModule` using your CurrencyUnit (de)serializer without having to register the whole `MoneyModule` because we might actually serialize our Monetary values differently from the format you've chosen in this library.

So, in reality, I actually have a need for some like a `CurrencyUnitModule` that is separate from the `MoneyModule`. However, I'm seeing that this is perhaps not what your library is intended to do, so I'm starting to feel like this is abusing your library.  Apologies for that. For now, I have just written my own Serializer/Deserializer for `CurrencyUnit`, but I would definitely use a module that only handles `CurrencyUnit`, FWIW.

**Comment by sappenin** [comment]
Closing this issue for now given my comment above. If you think of something that fits my use-case, feel free to re-open?
