### ISSUE TITLE
CurrencyUnitDeserializer throws UnknownCurrencyException if empty string is passed

### ISSUE THREAD

**Issue by ptahchiev** [zalando/jackson-datatype-money#76]
Hello I have a rest service and I want to set my currency to null. That's why I do a POST request specifying that `{currency:}` and on the server side I get the following exception:
```
Caused by: UnknownCurrencyException [currencyCode=]
	at javax.money.spi.MonetaryCurrenciesSingletonSpi.getCurrency(MonetaryCurrenciesSingletonSpi.java:74)
	at javax.money.Monetary.getCurrency(Monetary.java:422)
	at org.zalando.jackson.datatype.money.CurrencyUnitDeserializer.deserialize(CurrencyUnitDeserializer.java:25)
	at org.zalando.jackson.datatype.money.CurrencyUnitDeserializer.deserialize(CurrencyUnitDeserializer.java:12)
```

Looking at the `CurrencyUnitDeserializer` it looks like if an empty string is passed then the given exception will be raised:
````
    @Override
    public CurrencyUnit deserialize(final JsonParser parser, final DeserializationContext context) throws IOException {
        final String currencyCode = parser.getValueAsString();
        return Monetary.getCurrency(currencyCode);
    }
````
Can you please add a empty-string check so that if the value given is null or empty string then the method returns null.

**Comment by whiskeysierra** [comment]
`{currency:}` is invalid JSON. Are you sending `null` or an empty string?

**Comment by ptahchiev** [comment]
I'm calling it via rest and the `{currency:}` is printed in the google-chrome console. I believe it is sending an empty string.

**Comment by whiskeysierra** [comment]
Well, empty string is not a valid ISO currency code. Have you tried null?

**Comment by ptahchiev** [comment]
Even though it is not a valid ISO currency code I would argue that the deserializer should maybe return null.

**Comment by whiskeysierra** [comment]
The responsibility of the deserializer is to treat incoming strings as ISO currency codes and deserialize them as `CurrencyUnit`. The only special handling that I'd accept is `null` (in JSON) should become `null` (in Java). Empty strings are not `null` and they shouldn't be treated as equals.

Are you in control of the client that issues the request? Why can't you modify it to send the correct value?
